name: Build & Push Lambdas 
on:
  workflow_dispatch:
    # inputs:
    #   IMAGE_TAG:
    #     description: 'Translate Image Tag'
    #     required: false
    #     default: $(date + '%Y%m%d.%H%M')
  pull_request:
    branches:
      - main

env:
  PYTHON_VERSION: 3.12.2
  AWS_REGION: us-east-1
  # IMAGE_TAG: $(date + '%Y%m%d.%H%M')
  # IMAGE_TAG: 20240505.1

jobs:
  build:
    name: Build2Push
    permissions:
      contents: read
      issues: read
      checks: write
      pull-requests: write
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ env.PYTHON_VERSION }}
          cache: 'pip'
    
      - name: Setup AWS Test credentials
        run: |
          aws configure set region ${{ env.AWS_REGION }} --profile test
          aws configure set aws_access_key_id ${{ secrets.AWS_ACCESS_KEY_ID }} --profile test
          aws configure set aws_secret_access_key ${{ secrets.AWS_SECRET_ACCESS_KEY }} --profile test

      
      - name: Login to ECR
        run: |
          aws ecr get-login-password --region ${{ env.AWS_REGION }} --profile test | docker login --username AWS --password-stdin ${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.${{ env.AWS_REGION }}.amazonaws.com
  
          
      - name: Normal TAG
        run: |
            echo "IMAGE_TAG_EVAL=$(date +'%Y%m%d.%H%M')" >> $GITHUB_ENV
            echo $IMAGE_TAG_EVAL

      - name: VERSIONED TAG
        id: get_tags
        run: |
          
          echo "TAGS=$(git tag --points-at ${{ github.sha }} --list 'v*.*.*')" >> $GITHUB_ENV

      - name: Check if commit is tagged
        id: check_tag
        run: |
          V_TAG=${{ steps.get_tags.outputs.tags }}
          echo "Current commit is tagged with: $V_TAG"
          if [ -n "$V_TAG" ]; then
            echo "::set-output name=tagged::true"
          else
            echo "::set-output name=tagged::false"
          fi

      - name: Build Normal Image
        if: steps.check_tag.outputs.tagged == 'false'
        run: |
          chmod +x ci/scripts/build-and-push-lambda-image.sh
          python ci/scripts/build-and-push-all-lambdas.py  --config ci/configs/pipeline-config.json --gitsha $IMAGE_TAG_EVAL --registry ${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.${{ env.AWS_REGION }}.amazonaws.com


      - name: Build Versioned Image
        if: steps.check_tag.outputs.tagged == 'true'
        run: |
          V_TAG=${{ steps.get_tags.outputs.tags }}
          echo "Current commit is tagged with: $V_TAG"
          chmod +x ci/scripts/build-and-push-lambda-image.sh
          python ci/scripts/build-and-push-all-lambdas.py  --config ci/configs/pipeline-config.json --gitsha $V_TAG --registry ${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.${{ env.AWS_REGION }}.amazonaws.com
