name: TF Release
on:
  workflow_dispatch:
    inputs:
      IMAGE_TAG:
        description: 'Translate Image Tag - YYYYMMDD.HHSS'
        required: false
        default: 'latest'
  pull_request:
    branches:
      - main

env:
  AWS_REGION: us-east-1
  IMAGE_TAG: ${{ github.event.inputs.IMAGE_TAG || 'latest' }}
  # IMAGE_TAG: 20240505.1

jobs:
  terraform-release:
    name: "Terraform Release"
    runs-on: ubuntu-latest
    env:
      working-directory: ./environments
    steps:
      - uses: actions/checkout@v2

      - uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.8.2

      - name: Verify Terraform version
        run: terraform --version

      - name: Setup AWS Test credentials
        run: |
          aws configure set region ${{ env.AWS_REGION }} --profile test
          aws configure set aws_access_key_id ${{ secrets.AWS_ACCESS_KEY_ID }} --profile test
          aws configure set aws_secret_access_key ${{ secrets.AWS_SECRET_ACCESS_KEY }} --profile test

      - name: Generate TFVars
        run: |
          chmod +x ci/scripts/generate_tfvars.sh
          ci/scripts/generate_tfvars.sh test ${{ env.IMAGE_TAG }}

      - name: Check TFVars
        run: |
          cat terraform/environments/test/variables.tfvars

      - name: Terraform Plan
        if: ${{ github.event_name == 'pull_request' }}
        run: |
          chmod +x ci/scripts/aws-terraform-generic.sh
          python ci/scripts/aws-terraform.py  --config ci/configs/pipeline-config.json --command plan

      - name: Terraform Apply
        if: ${{ github.event_name != 'pull_request' }}
        run: |
          chmod +x ci/scripts/aws-terraform-generic.sh
          python ci/scripts/aws-terraform.py  --config ci/configs/pipeline-config.json --command apply
